server: 
  port: 9090
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp 

---

spring:
  profiles: local
  
  devtools:
    livereload:
      enabled: true
      
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/fy?characterEncoding=UTF-8&serverTimezone=UTC
      username: yedana
      password: 0715*

--- 

spring:
  profiles: prd

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/korea?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: ischus7156#

     